### ISSUE TITLE
`_generate_world_coords` is slow and uses a lot of memory 

### ISSUE THREAD

**Issue by nabobalis** [sunpy/ndcube#585] opened 2023-01-14 05:37 UTC
duplicate of #554
 
### Describe the performance issue

In irispy-lmsal, I noticed that one of my RTD examples was dying due to memory consumption.
I ran a profiler and found:
[
![Untitled](https://user-images.githubusercontent.com/1392107/212457627-e09f82e9-ca40-4676-a02c-dfc81e890c78.png)
](url)

I was creating a range of times by calling `.time` on a NDCube object. 
The data array is:

```
(Pdb) sji_1400.data.shape
(400, 417, 388)
```

Now I am using a gWCS so I am unclear if that makes the problem worse.

### To Reproduce

I don't have a concrete self-contained example right now. But I can try to create one if needed.

### Proposed fix

I saw this older PR (https://github.com/sunpy/ndcube/pull/474) but unsure if it would help.

Otherwise, I have no idea what could be done to fix it. Help would be great.

**Comment by wtbarnes** [comment] 2023-01-14 07:20
I wonder if this is related to #554. What does the correlation matrix look like for the IRIS data you mentioned?

**Comment by nabobalis** [comment] 2023-01-14 07:23
Mine is:
```
(Pdb) sji_1400.wcs.axis_correlation_matrix
array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False,  True]])
```

**Comment by Cadair** [comment] 2023-02-07 16:36
This is indeed a duplicate of #554 although thanks for the flame graph that's nice.
 
The fundamental issue here is that when you couple your spatial axes to your other axes you *need* to generate a 3D array of coordinates as the spatial coordinates change along the other axes, so there isn't really anything you can do to reduce the scale of the computation. We would need to profile the code, mostly in Astropy and try and improve performance that way.

**Comment by Cadair** [comment] 2023-02-07 16:37
The main thing I would ask people running into this is do you really *need* to be doing this computation for your whole array?

**Comment by nabobalis** [comment] 2023-02-07 17:33
> Can you show me the code you are running, getting all the timestamps shouldn't trigger a full 3D coord set.

The code is a large example which I have but the line is calling `.time` here: https://github.com/LM-SAL/irispy-lmsal/blob/c7aafeaccfa865e6eb6ac013798be7f322b6ebe3/examples/skip_umbral_flashes.py#L112

**Comment by Cadair** [comment] 2023-02-08 17:39
What's that calling?

**Comment by nabobalis** [comment] 2023-02-08 17:49
It actually is from sunraster: 
https://github.com/sunpy/sunraster/blob/main/sunraster/spectrogram.py#L361

But after calls: https://github.com/sunpy/sunraster/blob/main/sunraster/spectrogram.py#L444

Then that calls `axis_world_coords` which is in ndcube.

**Comment by Cadair** [comment] 2023-02-08 17:52
I think that's a bug then as in theory one should be able to slice out the time component of that WCS independent of space. This is still a dupe though.

**Comment by Cadair** [comment] 2023-02-08 17:54
yes

**Comment by nabobalis** [comment] 2024-11-08 19:35
![Screenshot_20241108_113459](https://github.com/user-attachments/assets/6b3ac0db-60ba-4142-87e1-df65e1ecab5f)

Still an issue.

**Comment by nabobalis** [comment] 2024-11-08 19:50
I wonder if this is actually a bug in sunraster.

**Closed** 2024-12-13 22:52 UTC
